# Generated by Django 4.2.8 on 2026-02-08 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('crop', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('remedy', models.JSONField()),
                ('prevention', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant Disease',
                'verbose_name_plural': 'Plant Diseases',
                'db_table': 'plant_diseases',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('is_healthy', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('predictions', models.JSONField(blank=True, null=True)),
                ('scan_method', models.CharField(choices=[('camera', 'Camera'), ('upload', 'Upload')], default='upload', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.plantdisease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'db_table': 'scan_history',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='CropInsectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=200)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('season', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=100)),
                ('insect_name', models.CharField(max_length=200)),
                ('insect_nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('insect_hindi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insect_common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insect_type', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_type', models.TextField(blank=True, null=True)),
                ('how_to_recognize', models.TextField(blank=True, null=True)),
                ('best_control_time', models.CharField(blank=True, max_length=200, null=True)),
                ('pesticide_options', models.TextField(blank=True, null=True)),
                ('mrp_2026', models.CharField(blank=True, max_length=100, null=True)),
                ('application_method', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crop_insect_data',
                'indexes': [models.Index(fields=['district', 'village'], name='crop_insect_distric_fc2ffd_idx'), models.Index(fields=['crop'], name='crop_insect_crop_78b6f6_idx'), models.Index(fields=['insect_name'], name='crop_insect_insect__707acf_idx')],
            },
        ),
    ]
