# Generated by Django 4.2.8 on 2026-03-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanhistory_dataset_matched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/'),
        ),
    ]
