# Generated by Django 4.2.8 on 2026-04-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0003_alter_scanhistory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanhistory',
            options={},
        ),
        migrations.RenameField(
            model_name='scanhistory',
            old_name='confidence',
            new_name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='dataset_matched',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='predictions',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='reference_data',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='scan_method',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='treatments',
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='disease_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='scanhistory',
            table=None,
        ),
    ]
