# Generated by Django 4.2.8 on 2026-04-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_scanhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='remedy_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
